name: Build Homebrew Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # This runs your steps INSIDE the official devkitPro environment
    container: devkitpro/devkitarm:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Additional Dependencies
        run: |
          dkp-pacman -Syu --noconfirm 3ds-dev 3ds-opusfile

      - name: Build Project
        run: |
          make

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: reShop build
          path: ./reShop.3dsx
