name: Build reShop

on:
  push:
    branches: [ "main" ]
    paths:
      - 'source/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'source/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Additional Dependencies
        run: |
          dkp-pacman -Syu --noconfirm 3ds-dev 3ds-opusfile

      - name: Build 3dsx
        run: |
          make
      - name: Build Project
        run: |
          make cia
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: reShop 3dsx
          path: ./reShop.3dsx
      - name: Upload Build Artifact 2️⃣
        uses: actions/upload-artifact@v4
        with:
          name: reShop cia
          path: ./reShop.cia
